MODEL_RES_PARTNER = ('id',
                     'name',
                     'street',
                     'street2',
                     'city',
                     'phone', )
MODEL_RES_USERS = ('id',
                   'name',
                   'is_service_partner',
                   'is_driver',
                   'is_towing_partner',
                   'service_partner_id',
                   'towing_partner_id',
                   'vehicle_owner_id',
                   'email', )
MODEL_SIMPLE_FIELDS = ('id',
                       'name')
MODEL_SIMPLE_SERVICE_FIELDS = ('id',
                               'service_reference')
MODEL_SIMPLE_TOWING_FIELDS = ('id',
                              'towing_reference')
MODEL_SIMPLE_PAYMENT_FIELDS = ('id',
                               'payment_reference')
MODEL_AUTO_MECHANIC = ('id',
                       'name',
                       'mobile',
                       'email',
                       'image',
                       'dob',
                       'auto_messiah_id',
                       'gender',
                       'state',
                       'service_state',
                       'no_of_jobs',
                       'no_of_rating',
                       'rating_score',
                       'gps_location',
                       'gps_longitude',
                       'gps_latitude',
                       'partner_type',
                       'gender',
                       'service_count',
                       'specialty',
                       ('service_request_ids', [(
                           'id',
                           ('mechanic_id', (  # many2one
                               MODEL_SIMPLE_FIELDS
                           )),
                           'service_amount',
                       )]),)
MODEL_AUTO_PAYMENT = ('id',
                      ('service_request_id', MODEL_SIMPLE_SERVICE_FIELDS),
                      ('towing_request_id',MODEL_SIMPLE_FIELDS),
                      'payment_mode',
                      'amount',
                      'state',
                      ('related_user_id', MODEL_SIMPLE_FIELDS),
                      ('mechanic_id', MODEL_SIMPLE_FIELDS),
                      ('towing_resource_id', MODEL_SIMPLE_FIELDS),
                      'payment_reference',
                      'payment_type',
                      'payment_time')
MODEL_AUTO_SERVICE = ('id',
                      'service_reference',
                      'service_amount',
                      'state',
                      'issue_reported',
                      'issue_diagnosed',
                      'service_start_time',
                      'service_end_time',
                      'amount_paid',
                      'amount_remain',
                      ('service_type_id', MODEL_SIMPLE_FIELDS),
                      ('mechanic_id', MODEL_SIMPLE_FIELDS),
                      ('related_user_id', MODEL_SIMPLE_FIELDS),
                      'service_request_date')
MODEL_AUTO_SUBSCRIPTION = ('id',
                           'name',
                           'start_date',
                           'end_date',
                           'state',
                           ('subscription_type_id', MODEL_SIMPLE_FIELDS))
MODEL_AUTO_TOWING = ('id',
                      'towing_reference',
                      'towing_amount',
                      'state',
                      'towing_start_time',
                      'towing_end_time',
                      'amount_paid',
                      'amount_remain',
                      'towing_start_point',
                      ('vehicle_id', ('id', 'license_plate')),
                      ('towing_resource_id', MODEL_SIMPLE_FIELDS),
                      ('related_user_id', MODEL_SIMPLE_FIELDS),
                      'towing_request_date')
MODEL_AUTO_TOWING_RESOURCE = ('id',
                       'name',
                       'mobile',
                       'email',
                       'dob',
                       'auto_messiah_id',
                       'gender',
                       'state',
                       'towing_state',
                       'no_of_jobs',
                       'no_of_rating',
                       'rating_score',
                       'gps_location',
                       'gps_longitude',
                       'gps_latitude',
                       'partner_type',
                       'gender',
                       'image',
                       'towing_count',
                       ('towing_request_ids', [(
                           'id',
                           ('towing_resource_id', (  # many2one
                               MODEL_SIMPLE_FIELDS
                           )),
                           'towing_amount',
                       )]),)
MODEL_AUTO_USER = ('id',
                   'name',
                   'user_type',
                   'gender',
                   'mobile',
                   'email',
                   'gps_longitude',
                   'gps_latitude',
                   'address',
                   ('current_subscription_id', MODEL_SIMPLE_FIELDS),
                   'subscription_start_date',
                   'subscription_expiry_date',
                   'image',
                   'subscription_status')
MODEL_AUTO_VEHICLE = ('id',
                     'license_plate',
                     'transmission',
                     'fuel_type',
                     ('model_id', MODEL_SIMPLE_FIELDS))
MODEL_AUTO_VEHICLE_BRAND = ('id',
                            'name',
                            'image')
MODEL_AUTO_VEHICLE_MODEL = ('id',
                            'name',
                            'image',
                            ('brand_id', MODEL_SIMPLE_FIELDS))
MODEL_AUTO_VEHICLE_SPARE_PART = ('id',
                                 'name',)
MODEL_AUTO_VEHICLE_SPARE_PART_PURCHASE = ('id',
                                          'purchase_by',
                                          'payment_mode',
                                          'purchase_reference',
                                          'order_date',
                                          ('auto_user_id', MODEL_SIMPLE_FIELDS),
                                          ('mechanic_id', MODEL_SIMPLE_FIELDS),
                                          'payment_id',
                                          'state',
                                          'total_amount')
MODEL_AUTO_VEHICLE_SPARE_PART_PURCHASE_LINE = ('id',
                                               'spare_part_name',
                                               'quantity',
                                               'unit_cost',
                                               'sub_total_cost',)
