{
    'name': 'Byte Inventory Management',
    'version': '10.0.1.0.0',
    'category': 'Accounts And Finance',
    'summary': 'Inventory Management',
    'description': 'Inventory Management',
    'author': 'Francis Bangura<francis@byteltd.com>',
    'website': 'http://byteltd.com',
    'depends': ['byte_core'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/inventory_subtraction_line.xml',
        'views/inventory_addition_line.xml',
        'views/inventory_item.xml',
        'views/inventory_account.xml',
        'views/inventory_addition.xml',
        'views/inventory_branch.xml',
        'views/inventory_department.xml',
        'views/inventory_uom.xml',
        'views/inventory_user.xml',
        'views/inventory_removal.xml',
        'views/inventory_supplier.xml',
        'views/inventory_adjustment.xml',
        'wizard/inventory_balance.xml',
        'wizard/inventory_gl_posting.xml',
        'wizard/inventory_valuation.xml',
        'wizard/inventory_move.xml',
        'menus/menus.xml',
        'data/data.xml',

    ],
    'installable': True,
}
